# Generated by Django 4.2.5 on 2023-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitteranalytics",
            name="followers_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="twitteranalytics",
            name="following_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="twitteranalytics",
            name="tweet_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
