# Generated by Django 4.2.5 on 2023-10-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter_analytics", "0002_alter_twitteranalytics_followers_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteranalytics",
            name="listed_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="twitteranalytics",
            name="mentions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="twitteranalytics",
            name="profile_visits",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="twitteranalytics",
            name="tweet_impressions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
